In [1]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

pygame 2.0.2 (SDL 2.0.16, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier('face.xml')
eye_cascade = cv2.CascadeClassifier('eye.xml')
model = load_model('model.h5')

In [19]:
mixer.init()
sound= mixer.Sound('alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=4)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,255,0), thickness=2 )
        
        # preprocessing steps
            eye= frame[ey:ey+eh,ex:ex+ew]
            eye= cv2.resize(eye,(80,80))
            eye= eye/255
            eye= eye.reshape(80,80,3)
            eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
            prediction = model.predict(eye)
            print(prediction)
       
        # if eyes are closed
        if prediction[0][1]<0.30:
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>10):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.90:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-5
            if (Score<10 or Score>25):
                Score=0
            
         
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[[5.3369929e-04 9.9946636e-01]]
[[6.824236e-06 9.999932e-01]]
[[0.47891158 0.5210884 ]]
[[1.7306475e-05 9.9998271e-01]]
[[0.2380739  0.76192605]]
[[0.00535759 0.9946424 ]]
[[0.6307586  0.36924142]]
[[5.475145e-07 9.999994e-01]]
[[0.3795882 0.6204118]]
[[0.74302703 0.25697294]]
[[7.282171e-06 9.999927e-01]]
[[3.2709633e-09 1.0000000e+00]]
[[0.57495576 0.42504424]]
[[7.0607734e-13 1.0000000e+00]]
[[0.2800915  0.71990854]]
[[0.08192049 0.9180795 ]]
[[0.5608674 0.4391326]]
[[0.8482928  0.15170717]]
[[0.2830264  0.71697366]]
[[0.24598575 0.7540143 ]]
[[0.18241532 0.8175847 ]]
[[2.2975406e-10 1.0000000e+00]]
[[0.28402132 0.7159787 ]]
[[0.68760854 0.31239152]]
[[0.1402017  0.85979825]]
[[0.01916566 0.9808343 ]]
[[0.23940393 0.7605961 ]]
[[0.00848926 0.9915107 ]]
[[0.94432694 0.05567306]]
[[0.7001091  0.29989088]]
[[0.9350388  0.06496117]]
[[0.16591552 0.8340845 ]]
[[0.22335604 0.77664393]]
[[0.04491086 0.95508915]]
[[0.34295803 0.65704197]]
[[0.0019526  0.99804735]]
[[0.864034 0.135966]]
[[0.